version: '3.9'

services:
  chroma:
    image: chromadb/chroma
    volumes:
      - chroma-data:/data
    restart: unless-stopped
    ports:
      - '8000:8000'

volumes:
  chroma-data:
    driver: local
